
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 11 2026 02:25:39 EDT (Mar 11 2026 06:25:39 UTC)

// Verification Directory fv/multiplier_top 

module multiplier_top(clk, rst_n, valid_in, ready_out, operand_a,
     operand_b, product, valid_out);
  input clk, rst_n, valid_in;
  input [15:0] operand_a, operand_b;
  output ready_out, valid_out;
  output [31:0] product;
  wire clk, rst_n, valid_in;
  wire [15:0] operand_a, operand_b;
  wire ready_out, valid_out;
  wire [31:0] product;
  wire [31:0] dadda_sum;
  wire [31:0] dadda_carry;
  wire [31:0] comb_product;
  wire n_0, \pp_array[0][0] , \pp_array[0][1] , \pp_array[0][2] ,
       \pp_array[0][3] , \pp_array[0][4] , \pp_array[0][5] ,
       \pp_array[0][6] ;
  wire \pp_array[0][7] , \pp_array[0][8] , \pp_array[0][9] ,
       \pp_array[0][10] , \pp_array[0][11] , \pp_array[0][12] ,
       \pp_array[0][13] , \pp_array[0][14] ;
  wire \pp_array[0][15] , \pp_array[0][16] , \pp_array[0][17] ,
       \pp_array[0][18] , \pp_array[0][19] , \pp_array[0][20] ,
       \pp_array[0][21] , \pp_array[0][22] ;
  wire \pp_array[0][23] , \pp_array[0][24] , \pp_array[0][25] ,
       \pp_array[0][26] , \pp_array[0][27] , \pp_array[0][28] ,
       \pp_array[0][29] , \pp_array[0][30] ;
  wire \pp_array[0][31] , \pp_array[1][0] , \pp_array[1][1] ,
       \pp_array[1][2] , \pp_array[1][3] , \pp_array[1][4] ,
       \pp_array[1][5] , \pp_array[1][6] ;
  wire \pp_array[1][7] , \pp_array[1][8] , \pp_array[1][9] ,
       \pp_array[1][10] , \pp_array[1][11] , \pp_array[1][12] ,
       \pp_array[1][13] , \pp_array[1][14] ;
  wire \pp_array[1][15] , \pp_array[1][16] , \pp_array[1][17] ,
       \pp_array[1][18] , \pp_array[1][19] , \pp_array[1][20] ,
       \pp_array[1][21] , \pp_array[1][22] ;
  wire \pp_array[1][23] , \pp_array[1][24] , \pp_array[1][25] ,
       \pp_array[1][26] , \pp_array[1][27] , \pp_array[1][28] ,
       \pp_array[1][29] , \pp_array[1][30] ;
  wire \pp_array[1][31] , \pp_array[2][0] , \pp_array[2][1] ,
       \pp_array[2][2] , \pp_array[2][3] , \pp_array[2][4] ,
       \pp_array[2][5] , \pp_array[2][6] ;
  wire \pp_array[2][7] , \pp_array[2][8] , \pp_array[2][9] ,
       \pp_array[2][10] , \pp_array[2][11] , \pp_array[2][12] ,
       \pp_array[2][13] , \pp_array[2][14] ;
  wire \pp_array[2][15] , \pp_array[2][16] , \pp_array[2][17] ,
       \pp_array[2][18] , \pp_array[2][19] , \pp_array[2][20] ,
       \pp_array[2][21] , \pp_array[2][22] ;
  wire \pp_array[2][23] , \pp_array[2][24] , \pp_array[2][25] ,
       \pp_array[2][26] , \pp_array[2][27] , \pp_array[2][28] ,
       \pp_array[2][29] , \pp_array[2][30] ;
  wire \pp_array[2][31] , \pp_array[3][0] , \pp_array[3][1] ,
       \pp_array[3][2] , \pp_array[3][3] , \pp_array[3][4] ,
       \pp_array[3][5] , \pp_array[3][6] ;
  wire \pp_array[3][7] , \pp_array[3][8] , \pp_array[3][9] ,
       \pp_array[3][10] , \pp_array[3][11] , \pp_array[3][12] ,
       \pp_array[3][13] , \pp_array[3][14] ;
  wire \pp_array[3][15] , \pp_array[3][16] , \pp_array[3][17] ,
       \pp_array[3][18] , \pp_array[3][19] , \pp_array[3][20] ,
       \pp_array[3][21] , \pp_array[3][22] ;
  wire \pp_array[3][23] , \pp_array[3][24] , \pp_array[3][25] ,
       \pp_array[3][26] , \pp_array[3][27] , \pp_array[3][28] ,
       \pp_array[3][29] , \pp_array[3][30] ;
  wire \pp_array[3][31] , \pp_array[4][0] , \pp_array[4][1] ,
       \pp_array[4][2] , \pp_array[4][3] , \pp_array[4][4] ,
       \pp_array[4][5] , \pp_array[4][6] ;
  wire \pp_array[4][7] , \pp_array[4][8] , \pp_array[4][9] ,
       \pp_array[4][10] , \pp_array[4][11] , \pp_array[4][12] ,
       \pp_array[4][13] , \pp_array[4][14] ;
  wire \pp_array[4][15] , \pp_array[4][16] , \pp_array[4][17] ,
       \pp_array[4][18] , \pp_array[4][19] , \pp_array[4][20] ,
       \pp_array[4][21] , \pp_array[4][22] ;
  wire \pp_array[4][23] , \pp_array[4][24] , \pp_array[4][25] ,
       \pp_array[4][26] , \pp_array[4][27] , \pp_array[4][28] ,
       \pp_array[4][29] , \pp_array[4][30] ;
  wire \pp_array[4][31] , \pp_array[5][0] , \pp_array[5][1] ,
       \pp_array[5][2] , \pp_array[5][3] , \pp_array[5][4] ,
       \pp_array[5][5] , \pp_array[5][6] ;
  wire \pp_array[5][7] , \pp_array[5][8] , \pp_array[5][9] ,
       \pp_array[5][10] , \pp_array[5][11] , \pp_array[5][12] ,
       \pp_array[5][13] , \pp_array[5][14] ;
  wire \pp_array[5][15] , \pp_array[5][16] , \pp_array[5][17] ,
       \pp_array[5][18] , \pp_array[5][19] , \pp_array[5][20] ,
       \pp_array[5][21] , \pp_array[5][22] ;
  wire \pp_array[5][23] , \pp_array[5][24] , \pp_array[5][25] ,
       \pp_array[5][26] , \pp_array[5][27] , \pp_array[5][28] ,
       \pp_array[5][29] , \pp_array[5][30] ;
  wire \pp_array[5][31] , \pp_array[6][0] , \pp_array[6][1] ,
       \pp_array[6][2] , \pp_array[6][3] , \pp_array[6][4] ,
       \pp_array[6][5] , \pp_array[6][6] ;
  wire \pp_array[6][7] , \pp_array[6][8] , \pp_array[6][9] ,
       \pp_array[6][10] , \pp_array[6][11] , \pp_array[6][12] ,
       \pp_array[6][13] , \pp_array[6][14] ;
  wire \pp_array[6][15] , \pp_array[6][16] , \pp_array[6][17] ,
       \pp_array[6][18] , \pp_array[6][19] , \pp_array[6][20] ,
       \pp_array[6][21] , \pp_array[6][22] ;
  wire \pp_array[6][23] , \pp_array[6][24] , \pp_array[6][25] ,
       \pp_array[6][26] , \pp_array[6][27] , \pp_array[6][28] ,
       \pp_array[6][29] , \pp_array[6][30] ;
  wire \pp_array[6][31] , \pp_array[7][0] , \pp_array[7][1] ,
       \pp_array[7][2] , \pp_array[7][3] , \pp_array[7][4] ,
       \pp_array[7][5] , \pp_array[7][6] ;
  wire \pp_array[7][7] , \pp_array[7][8] , \pp_array[7][9] ,
       \pp_array[7][10] , \pp_array[7][11] , \pp_array[7][12] ,
       \pp_array[7][13] , \pp_array[7][14] ;
  wire \pp_array[7][15] , \pp_array[7][16] , \pp_array[7][17] ,
       \pp_array[7][18] , \pp_array[7][19] , \pp_array[7][20] ,
       \pp_array[7][21] , \pp_array[7][22] ;
  wire \pp_array[7][23] , \pp_array[7][24] , \pp_array[7][25] ,
       \pp_array[7][26] , \pp_array[7][27] , \pp_array[7][28] ,
       \pp_array[7][29] , \pp_array[7][30] ;
  wire \pp_array[7][31] ;
  dadda_reduction_tree_WIDTH16_NUM_PP8_PROD_W32 u_dadda(.pp_in
       ({\pp_array[0][31] , \pp_array[0][30] , \pp_array[0][29] ,
       \pp_array[0][28] , \pp_array[0][27] , \pp_array[0][26] ,
       \pp_array[0][25] , \pp_array[0][24] , \pp_array[0][23] ,
       \pp_array[0][22] , \pp_array[0][21] , \pp_array[0][20] ,
       \pp_array[0][19] , \pp_array[0][18] , \pp_array[0][17] ,
       \pp_array[0][16] , \pp_array[0][15] , \pp_array[0][14] ,
       \pp_array[0][13] , \pp_array[0][12] , \pp_array[0][11] ,
       \pp_array[0][10] , \pp_array[0][9] , \pp_array[0][8] ,
       \pp_array[0][7] , \pp_array[0][6] , \pp_array[0][5] ,
       \pp_array[0][4] , \pp_array[0][3] , \pp_array[0][2] ,
       \pp_array[0][1] , \pp_array[0][0] , \pp_array[1][31] ,
       \pp_array[1][30] , \pp_array[1][29] , \pp_array[1][28] ,
       \pp_array[1][27] , \pp_array[1][26] , \pp_array[1][25] ,
       \pp_array[1][24] , \pp_array[1][23] , \pp_array[1][22] ,
       \pp_array[1][21] , \pp_array[1][20] , \pp_array[1][19] ,
       \pp_array[1][18] , \pp_array[1][17] , \pp_array[1][16] ,
       \pp_array[1][15] , \pp_array[1][14] , \pp_array[1][13] ,
       \pp_array[1][12] , \pp_array[1][11] , \pp_array[1][10] ,
       \pp_array[1][9] , \pp_array[1][8] , \pp_array[1][7] ,
       \pp_array[1][6] , \pp_array[1][5] , \pp_array[1][4] ,
       \pp_array[1][3] , \pp_array[1][2] , \pp_array[1][1] ,
       \pp_array[1][0] , \pp_array[2][31] , \pp_array[2][30] ,
       \pp_array[2][29] , \pp_array[2][28] , \pp_array[2][27] ,
       \pp_array[2][26] , \pp_array[2][25] , \pp_array[2][24] ,
       \pp_array[2][23] , \pp_array[2][22] , \pp_array[2][21] ,
       \pp_array[2][20] , \pp_array[2][19] , \pp_array[2][18] ,
       \pp_array[2][17] , \pp_array[2][16] , \pp_array[2][15] ,
       \pp_array[2][14] , \pp_array[2][13] , \pp_array[2][12] ,
       \pp_array[2][11] , \pp_array[2][10] , \pp_array[2][9] ,
       \pp_array[2][8] , \pp_array[2][7] , \pp_array[2][6] ,
       \pp_array[2][5] , \pp_array[2][4] , \pp_array[2][3] ,
       \pp_array[2][2] , \pp_array[2][1] , \pp_array[2][0] ,
       \pp_array[3][31] , \pp_array[3][30] , \pp_array[3][29] ,
       \pp_array[3][28] , \pp_array[3][27] , \pp_array[3][26] ,
       \pp_array[3][25] , \pp_array[3][24] , \pp_array[3][23] ,
       \pp_array[3][22] , \pp_array[3][21] , \pp_array[3][20] ,
       \pp_array[3][19] , \pp_array[3][18] , \pp_array[3][17] ,
       \pp_array[3][16] , \pp_array[3][15] , \pp_array[3][14] ,
       \pp_array[3][13] , \pp_array[3][12] , \pp_array[3][11] ,
       \pp_array[3][10] , \pp_array[3][9] , \pp_array[3][8] ,
       \pp_array[3][7] , \pp_array[3][6] , \pp_array[3][5] ,
       \pp_array[3][4] , \pp_array[3][3] , \pp_array[3][2] ,
       \pp_array[3][1] , \pp_array[3][0] , \pp_array[4][31] ,
       \pp_array[4][30] , \pp_array[4][29] , \pp_array[4][28] ,
       \pp_array[4][27] , \pp_array[4][26] , \pp_array[4][25] ,
       \pp_array[4][24] , \pp_array[4][23] , \pp_array[4][22] ,
       \pp_array[4][21] , \pp_array[4][20] , \pp_array[4][19] ,
       \pp_array[4][18] , \pp_array[4][17] , \pp_array[4][16] ,
       \pp_array[4][15] , \pp_array[4][14] , \pp_array[4][13] ,
       \pp_array[4][12] , \pp_array[4][11] , \pp_array[4][10] ,
       \pp_array[4][9] , \pp_array[4][8] , \pp_array[4][7] ,
       \pp_array[4][6] , \pp_array[4][5] , \pp_array[4][4] ,
       \pp_array[4][3] , \pp_array[4][2] , \pp_array[4][1] ,
       \pp_array[4][0] , \pp_array[5][31] , \pp_array[5][30] ,
       \pp_array[5][29] , \pp_array[5][28] , \pp_array[5][27] ,
       \pp_array[5][26] , \pp_array[5][25] , \pp_array[5][24] ,
       \pp_array[5][23] , \pp_array[5][22] , \pp_array[5][21] ,
       \pp_array[5][20] , \pp_array[5][19] , \pp_array[5][18] ,
       \pp_array[5][17] , \pp_array[5][16] , \pp_array[5][15] ,
       \pp_array[5][14] , \pp_array[5][13] , \pp_array[5][12] ,
       \pp_array[5][11] , \pp_array[5][10] , \pp_array[5][9] ,
       \pp_array[5][8] , \pp_array[5][7] , \pp_array[5][6] ,
       \pp_array[5][5] , \pp_array[5][4] , \pp_array[5][3] ,
       \pp_array[5][2] , \pp_array[5][1] , \pp_array[5][0] ,
       \pp_array[6][31] , \pp_array[6][30] , \pp_array[6][29] ,
       \pp_array[6][28] , \pp_array[6][27] , \pp_array[6][26] ,
       \pp_array[6][25] , \pp_array[6][24] , \pp_array[6][23] ,
       \pp_array[6][22] , \pp_array[6][21] , \pp_array[6][20] ,
       \pp_array[6][19] , \pp_array[6][18] , \pp_array[6][17] ,
       \pp_array[6][16] , \pp_array[6][15] , \pp_array[6][14] ,
       \pp_array[6][13] , \pp_array[6][12] , \pp_array[6][11] ,
       \pp_array[6][10] , \pp_array[6][9] , \pp_array[6][8] ,
       \pp_array[6][7] , \pp_array[6][6] , \pp_array[6][5] ,
       \pp_array[6][4] , \pp_array[6][3] , \pp_array[6][2] ,
       \pp_array[6][1] , \pp_array[6][0] , \pp_array[7][31] ,
       \pp_array[7][30] , \pp_array[7][29] , \pp_array[7][28] ,
       \pp_array[7][27] , \pp_array[7][26] , \pp_array[7][25] ,
       \pp_array[7][24] , \pp_array[7][23] , \pp_array[7][22] ,
       \pp_array[7][21] , \pp_array[7][20] , \pp_array[7][19] ,
       \pp_array[7][18] , \pp_array[7][17] , \pp_array[7][16] ,
       \pp_array[7][15] , \pp_array[7][14] , \pp_array[7][13] ,
       \pp_array[7][12] , \pp_array[7][11] , \pp_array[7][10] ,
       \pp_array[7][9] , \pp_array[7][8] , \pp_array[7][7] ,
       \pp_array[7][6] , \pp_array[7][5] , \pp_array[7][4] ,
       \pp_array[7][3] , \pp_array[7][2] , \pp_array[7][1] ,
       \pp_array[7][0] }), .sum_out (dadda_sum), .carry_out
       (dadda_carry));
  final_adder_PROD_W32 u_fa(.sum_in (dadda_sum), .carry_in
       (dadda_carry), .result (comb_product));
  partial_product_generator_WIDTH16_NUM_PP8_PROD_W32 u_ppg(.A
       (operand_a), .B (operand_b), .pp ({\pp_array[0][31] ,
       \pp_array[0][30] , \pp_array[0][29] , \pp_array[0][28] ,
       \pp_array[0][27] , \pp_array[0][26] , \pp_array[0][25] ,
       \pp_array[0][24] , \pp_array[0][23] , \pp_array[0][22] ,
       \pp_array[0][21] , \pp_array[0][20] , \pp_array[0][19] ,
       \pp_array[0][18] , \pp_array[0][17] , \pp_array[0][16] ,
       \pp_array[0][15] , \pp_array[0][14] , \pp_array[0][13] ,
       \pp_array[0][12] , \pp_array[0][11] , \pp_array[0][10] ,
       \pp_array[0][9] , \pp_array[0][8] , \pp_array[0][7] ,
       \pp_array[0][6] , \pp_array[0][5] , \pp_array[0][4] ,
       \pp_array[0][3] , \pp_array[0][2] , \pp_array[0][1] ,
       \pp_array[0][0] , \pp_array[1][31] , \pp_array[1][30] ,
       \pp_array[1][29] , \pp_array[1][28] , \pp_array[1][27] ,
       \pp_array[1][26] , \pp_array[1][25] , \pp_array[1][24] ,
       \pp_array[1][23] , \pp_array[1][22] , \pp_array[1][21] ,
       \pp_array[1][20] , \pp_array[1][19] , \pp_array[1][18] ,
       \pp_array[1][17] , \pp_array[1][16] , \pp_array[1][15] ,
       \pp_array[1][14] , \pp_array[1][13] , \pp_array[1][12] ,
       \pp_array[1][11] , \pp_array[1][10] , \pp_array[1][9] ,
       \pp_array[1][8] , \pp_array[1][7] , \pp_array[1][6] ,
       \pp_array[1][5] , \pp_array[1][4] , \pp_array[1][3] ,
       \pp_array[1][2] , \pp_array[1][1] , \pp_array[1][0] ,
       \pp_array[2][31] , \pp_array[2][30] , \pp_array[2][29] ,
       \pp_array[2][28] , \pp_array[2][27] , \pp_array[2][26] ,
       \pp_array[2][25] , \pp_array[2][24] , \pp_array[2][23] ,
       \pp_array[2][22] , \pp_array[2][21] , \pp_array[2][20] ,
       \pp_array[2][19] , \pp_array[2][18] , \pp_array[2][17] ,
       \pp_array[2][16] , \pp_array[2][15] , \pp_array[2][14] ,
       \pp_array[2][13] , \pp_array[2][12] , \pp_array[2][11] ,
       \pp_array[2][10] , \pp_array[2][9] , \pp_array[2][8] ,
       \pp_array[2][7] , \pp_array[2][6] , \pp_array[2][5] ,
       \pp_array[2][4] , \pp_array[2][3] , \pp_array[2][2] ,
       \pp_array[2][1] , \pp_array[2][0] , \pp_array[3][31] ,
       \pp_array[3][30] , \pp_array[3][29] , \pp_array[3][28] ,
       \pp_array[3][27] , \pp_array[3][26] , \pp_array[3][25] ,
       \pp_array[3][24] , \pp_array[3][23] , \pp_array[3][22] ,
       \pp_array[3][21] , \pp_array[3][20] , \pp_array[3][19] ,
       \pp_array[3][18] , \pp_array[3][17] , \pp_array[3][16] ,
       \pp_array[3][15] , \pp_array[3][14] , \pp_array[3][13] ,
       \pp_array[3][12] , \pp_array[3][11] , \pp_array[3][10] ,
       \pp_array[3][9] , \pp_array[3][8] , \pp_array[3][7] ,
       \pp_array[3][6] , \pp_array[3][5] , \pp_array[3][4] ,
       \pp_array[3][3] , \pp_array[3][2] , \pp_array[3][1] ,
       \pp_array[3][0] , \pp_array[4][31] , \pp_array[4][30] ,
       \pp_array[4][29] , \pp_array[4][28] , \pp_array[4][27] ,
       \pp_array[4][26] , \pp_array[4][25] , \pp_array[4][24] ,
       \pp_array[4][23] , \pp_array[4][22] , \pp_array[4][21] ,
       \pp_array[4][20] , \pp_array[4][19] , \pp_array[4][18] ,
       \pp_array[4][17] , \pp_array[4][16] , \pp_array[4][15] ,
       \pp_array[4][14] , \pp_array[4][13] , \pp_array[4][12] ,
       \pp_array[4][11] , \pp_array[4][10] , \pp_array[4][9] ,
       \pp_array[4][8] , \pp_array[4][7] , \pp_array[4][6] ,
       \pp_array[4][5] , \pp_array[4][4] , \pp_array[4][3] ,
       \pp_array[4][2] , \pp_array[4][1] , \pp_array[4][0] ,
       \pp_array[5][31] , \pp_array[5][30] , \pp_array[5][29] ,
       \pp_array[5][28] , \pp_array[5][27] , \pp_array[5][26] ,
       \pp_array[5][25] , \pp_array[5][24] , \pp_array[5][23] ,
       \pp_array[5][22] , \pp_array[5][21] , \pp_array[5][20] ,
       \pp_array[5][19] , \pp_array[5][18] , \pp_array[5][17] ,
       \pp_array[5][16] , \pp_array[5][15] , \pp_array[5][14] ,
       \pp_array[5][13] , \pp_array[5][12] , \pp_array[5][11] ,
       \pp_array[5][10] , \pp_array[5][9] , \pp_array[5][8] ,
       \pp_array[5][7] , \pp_array[5][6] , \pp_array[5][5] ,
       \pp_array[5][4] , \pp_array[5][3] , \pp_array[5][2] ,
       \pp_array[5][1] , \pp_array[5][0] , \pp_array[6][31] ,
       \pp_array[6][30] , \pp_array[6][29] , \pp_array[6][28] ,
       \pp_array[6][27] , \pp_array[6][26] , \pp_array[6][25] ,
       \pp_array[6][24] , \pp_array[6][23] , \pp_array[6][22] ,
       \pp_array[6][21] , \pp_array[6][20] , \pp_array[6][19] ,
       \pp_array[6][18] , \pp_array[6][17] , \pp_array[6][16] ,
       \pp_array[6][15] , \pp_array[6][14] , \pp_array[6][13] ,
       \pp_array[6][12] , \pp_array[6][11] , \pp_array[6][10] ,
       \pp_array[6][9] , \pp_array[6][8] , \pp_array[6][7] ,
       \pp_array[6][6] , \pp_array[6][5] , \pp_array[6][4] ,
       \pp_array[6][3] , \pp_array[6][2] , \pp_array[6][1] ,
       \pp_array[6][0] , \pp_array[7][31] , \pp_array[7][30] ,
       \pp_array[7][29] , \pp_array[7][28] , \pp_array[7][27] ,
       \pp_array[7][26] , \pp_array[7][25] , \pp_array[7][24] ,
       \pp_array[7][23] , \pp_array[7][22] , \pp_array[7][21] ,
       \pp_array[7][20] , \pp_array[7][19] , \pp_array[7][18] ,
       \pp_array[7][17] , \pp_array[7][16] , \pp_array[7][15] ,
       \pp_array[7][14] , \pp_array[7][13] , \pp_array[7][12] ,
       \pp_array[7][11] , \pp_array[7][10] , \pp_array[7][9] ,
       \pp_array[7][8] , \pp_array[7][7] , \pp_array[7][6] ,
       \pp_array[7][5] , \pp_array[7][4] , \pp_array[7][3] ,
       \pp_array[7][2] , \pp_array[7][1] , \pp_array[7][0] }));
  SDFFRHQX2 \product_reg[25] (.RN (rst_n), .CK (clk), .D (product[25]),
       .SE (n_0), .SI (comb_product[25]), .Q (product[25]));
  SDFFRHQX2 \product_reg[1] (.RN (rst_n), .CK (clk), .D (product[1]),
       .SE (n_0), .SI (comb_product[1]), .Q (product[1]));
  SDFFRHQX2 \product_reg[14] (.RN (rst_n), .CK (clk), .D (product[14]),
       .SE (n_0), .SI (comb_product[14]), .Q (product[14]));
  SDFFRHQX2 \product_reg[15] (.RN (rst_n), .CK (clk), .D (product[15]),
       .SE (n_0), .SI (comb_product[15]), .Q (product[15]));
  SDFFRHQX2 \product_reg[16] (.RN (rst_n), .CK (clk), .D (product[16]),
       .SE (n_0), .SI (comb_product[16]), .Q (product[16]));
  SDFFRHQX2 \product_reg[17] (.RN (rst_n), .CK (clk), .D (product[17]),
       .SE (n_0), .SI (comb_product[17]), .Q (product[17]));
  SDFFRHQX2 \product_reg[18] (.RN (rst_n), .CK (clk), .D (product[18]),
       .SE (n_0), .SI (comb_product[18]), .Q (product[18]));
  SDFFRHQX2 \product_reg[19] (.RN (rst_n), .CK (clk), .D (product[19]),
       .SE (n_0), .SI (comb_product[19]), .Q (product[19]));
  SDFFRHQX2 \product_reg[20] (.RN (rst_n), .CK (clk), .D (product[20]),
       .SE (n_0), .SI (comb_product[20]), .Q (product[20]));
  SDFFRHQX2 \product_reg[21] (.RN (rst_n), .CK (clk), .D (product[21]),
       .SE (n_0), .SI (comb_product[21]), .Q (product[21]));
  SDFFRHQX2 \product_reg[2] (.RN (rst_n), .CK (clk), .D (product[2]),
       .SE (n_0), .SI (comb_product[2]), .Q (product[2]));
  SDFFRHQX2 \product_reg[3] (.RN (rst_n), .CK (clk), .D (product[3]),
       .SE (n_0), .SI (comb_product[3]), .Q (product[3]));
  SDFFRHQX2 \product_reg[22] (.RN (rst_n), .CK (clk), .D (product[22]),
       .SE (n_0), .SI (comb_product[22]), .Q (product[22]));
  SDFFRHQX2 \product_reg[23] (.RN (rst_n), .CK (clk), .D (product[23]),
       .SE (n_0), .SI (comb_product[23]), .Q (product[23]));
  SDFFRHQX2 \product_reg[24] (.RN (rst_n), .CK (clk), .D (product[24]),
       .SE (n_0), .SI (comb_product[24]), .Q (product[24]));
  SDFFRHQX2 \product_reg[0] (.RN (rst_n), .CK (clk), .D (product[0]),
       .SE (n_0), .SI (comb_product[0]), .Q (product[0]));
  SDFFRHQX2 \product_reg[13] (.RN (rst_n), .CK (clk), .D (product[13]),
       .SE (n_0), .SI (comb_product[13]), .Q (product[13]));
  SDFFRHQX2 \product_reg[26] (.RN (rst_n), .CK (clk), .D (product[26]),
       .SE (n_0), .SI (comb_product[26]), .Q (product[26]));
  SDFFRHQX2 \product_reg[27] (.RN (rst_n), .CK (clk), .D (product[27]),
       .SE (n_0), .SI (comb_product[27]), .Q (product[27]));
  SDFFRHQX2 \product_reg[5] (.RN (rst_n), .CK (clk), .D (product[5]),
       .SE (n_0), .SI (comb_product[5]), .Q (product[5]));
  SDFFRHQX2 \product_reg[28] (.RN (rst_n), .CK (clk), .D (product[28]),
       .SE (n_0), .SI (comb_product[28]), .Q (product[28]));
  SDFFRHQX2 \product_reg[29] (.RN (rst_n), .CK (clk), .D (product[29]),
       .SE (n_0), .SI (comb_product[29]), .Q (product[29]));
  SDFFRHQX2 \product_reg[6] (.RN (rst_n), .CK (clk), .D (product[6]),
       .SE (n_0), .SI (comb_product[6]), .Q (product[6]));
  SDFFRHQX2 \product_reg[7] (.RN (rst_n), .CK (clk), .D (product[7]),
       .SE (n_0), .SI (comb_product[7]), .Q (product[7]));
  SDFFRHQX2 \product_reg[30] (.RN (rst_n), .CK (clk), .D (product[30]),
       .SE (n_0), .SI (comb_product[30]), .Q (product[30]));
  SDFFRHQX2 \product_reg[31] (.RN (rst_n), .CK (clk), .D (product[31]),
       .SE (n_0), .SI (comb_product[31]), .Q (product[31]));
  SDFFRHQX2 \product_reg[8] (.RN (rst_n), .CK (clk), .D (product[8]),
       .SE (n_0), .SI (comb_product[8]), .Q (product[8]));
  SDFFRHQX2 \product_reg[9] (.RN (rst_n), .CK (clk), .D (product[9]),
       .SE (n_0), .SI (comb_product[9]), .Q (product[9]));
  SDFFRHQX2 \product_reg[10] (.RN (rst_n), .CK (clk), .D (product[10]),
       .SE (n_0), .SI (comb_product[10]), .Q (product[10]));
  SDFFRHQX2 \product_reg[11] (.RN (rst_n), .CK (clk), .D (product[11]),
       .SE (n_0), .SI (comb_product[11]), .Q (product[11]));
  SDFFRHQX2 \product_reg[12] (.RN (rst_n), .CK (clk), .D (product[12]),
       .SE (n_0), .SI (comb_product[12]), .Q (product[12]));
  SDFFRHQX2 \product_reg[4] (.RN (rst_n), .CK (clk), .D (product[4]),
       .SE (n_0), .SI (comb_product[4]), .Q (product[4]));
  NOR2BX4 g2(.AN (valid_in), .B (valid_out), .Y (n_0));
  DFFRX4 valid_out_reg(.RN (rst_n), .CK (clk), .D (valid_in), .Q
       (valid_out), .QN (ready_out));
endmodule

